version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
build.include_nuget_references: true
dotnet_csproj:
  patch: true
  file: 'TaskBoardAssistant/TaskBoardAssistant/TaskBoardAssistant.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  artifact: /.*\.nupkg/
  on:
    branch: master